layout_spectrum: 0.03191489
name: JetRing
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.2952479
  saturation: 0.07682603
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  lightness: 0.5357209
  rhythmicContrast: 0.6138921
typography_spectrum: 0.08525842
